name: "❓ Ask for help"
description: "Get help installing, configuring or using Dockge"
labels: [help]
body:
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "⚠️ Please verify that this question has NOT been asked before."
      description: "Search the issues by clicking [HERE](https://github.com/darthrater78/dockge/issues?q=)"
      options:
        - label: "I checked and didn't find a similar question"
          required: true
  - type: textarea
    id: question
    validations:
      required: true
    attributes:
      label: "📝 What do you need help with?"
      description: "Describe what you are trying to do, what you tried, and what happened. Remove any secrets from logs and compose files."
  - type: input
    id: dockge-version
    validations:
      required: true
    attributes:
      label: "🐻 Dockge Version"
      placeholder: "e.g. 2.2.0"
