name: "🚀 Feature Request"
description: "Suggest an idea for Dockge"
labels: [enhancement]
body:
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "⚠️ Please verify that this feature has NOT been requested before."
      description: "Search the issues by clicking [HERE](https://github.com/darthrater78/dockge/issues?q=)"
      options:
        - label: "I checked and didn't find a similar request"
          required: true
  - type: textarea
    id: feature
    validations:
      required: true
    attributes:
      label: "🔖 Feature description"
      description: "What problem does it solve, and how would you like it to work?"
